---
#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: true
